apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: venafi-tpp-pingpong-issuer
  namespace: default
spec:
  venafi:
    zone: "TLS/SSL\\Certificates\\Jetstack-short"
    tpp:
      url: https://<instance hostname>/vedsdk # Change this to the URL of your TPP instance
      credentialsRef:
        name: tpp-auth-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ping-certificate
  namespace: default
spec:
  renewBefore: 30m
  secretName: ping-tls
  subject:
    organizations:
      - Example Organization
  dnsNames:
    - ping-service.default.svc.cluster.local
  issuerRef:
    name: venafi-tpp-pingpong-issuer
    kind: Issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pong-certificate
  namespace: default
spec:
  renewBefore: 30m
  secretName: pong-tls
  subject:
    organizations:
      - Example Organization
  dnsNames:
    - pong-service.default.svc.cluster.local
  issuerRef:
    name: venafi-tpp-pingpong-issuer
    kind: Issuer
---
apiVersion:  apps/v1
kind: Deployment
metadata:
  labels:
    app: ping
  name: ping-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
        - image: demo.cert-manager.io/pingpong:local
          name: pingpong
          command:
            - /usr/local/bin/pingpong
            - -endpoint=https://pong-service.default.svc.cluster.local:8443/ping
            - -ca-file=/etc/ssl/private/tls.crt
            - -cert-file=/etc/ssl/private/tls.crt
            - -key-file=/etc/ssl/private/tls.key
          volumeMounts:
            - mountPath: "/etc/ssl/private"
              name: ping-tls
              readOnly: true
          ports:
            - containerPort: 8443
              name: internal-https
            - containerPort: 9443
              name: external-https
      volumes:
        - name: ping-tls
          secret:
            secretName: ping-tls
---
apiVersion:  apps/v1
kind: Deployment
metadata:
  labels:
    app: pong
  name: pong-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
        - image: demo.cert-manager.io/pingpong:local
          name: pingpong
          command:
            - /usr/local/bin/pingpong
            - -endpoint=https://ping-service.default.svc.cluster.local:8443/ping
            - -ca-file=/etc/ssl/private/tls.crt
            - -cert-file=/etc/ssl/private/tls.crt
            - -key-file=/etc/ssl/private/tls.key
          volumeMounts:
            - mountPath: "/etc/ssl/private"
              name: pong-tls
              readOnly: true
          ports:
            - containerPort: 8443
              name: internal-https
            - containerPort: 9443
              name: external-https
      volumes:
        - name: pong-tls
          secret:
            secretName: pong-tls
---
apiVersion: v1
kind: Service
metadata:
  name: ping-service
  namespace: default
spec:
  type: NodePort
  ports:
    - name: internal-https
      port: 8443
      protocol: TCP
      targetPort: internal-https
    - name: https
      port: 9443
      protocol: TCP
      targetPort: external-https
  selector:
    app: ping
---
apiVersion: v1
kind: Service
metadata:
  name: pong-service
  namespace: default
spec:
  type: NodePort
  ports:
    - name: internal-https
      port: 8443
      protocol: TCP
      targetPort: internal-https
    - name: https
      port: 9443
      protocol: TCP
      targetPort: external-https
  selector:
    app: pong
